CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  f_name VARCHAR(255) NOT NULL,
  l_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE shows (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  descr VARCHAR(255) NOT NULL,
  dt  DATETIME(3) NOT NULL
);