CREATE TABLE users (
  id INTEGER NOT NULL AUTO_INCREMENT,
  f_name VARCHAR(255) NOT NULL,
  l_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE shows (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  descr VARCHAR(255) NOT NULL,
  dt  DATETIME(3),
  PRIMARY KEY(id)
);